### ISSUE TITLE
CT recalculateVelocityAndAcceleration

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/normal-modes#88] opened 2021-12-10 15:44 UTC
```
normal-modes : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/normal-modes/normal-modes_en.html?continuousTest=%7B%22test%22%3A%5B%22normal-modes%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639119391778%22%2C%22timestamp%22%3A1639121460179%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: recalculateVelocityAndAcceleration: N=10 i=1 velocity=Vector2(0.3219868106007756, 0), expected non-zero y component
Error: Assertion failed: recalculateVelocityAndAcceleration: N=10 i=1 velocity=Vector2(0.3219868106007756, 0), expected non-zero y component
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/assert/js/assert.js:25:13)
at OneDimensionModel.recalculateVelocityAndAcceleration (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/normal-modes/js/one-dimension/model/OneDimensionModel.js:291:13)
at OneDimensionModel.setVerletPositions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/normal-modes/js/one-dimension/model/OneDimensionModel.js:257:10)
at OneDimensionModel.singleStep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/normal-modes/js/one-dimension/model/OneDimensionModel.js:230:12)
at OneDimensionModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/normal-modes/js/one-dimension/model/OneDimensionModel.js:210:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/joist/js/Sim.js:258:22
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/axon/js/Action.js:195:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/joist/js/Sim.js:787:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/joist/js/Sim.js:776:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/joist/js/Sim.js:757:12)
id: Bayes Chrome
Snapshot from 12/9/2021, 11:56:31 PM

----------------------------------

normal-modes : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/normal-modes/normal-modes_en.html?continuousTest=%7B%22test%22%3A%5B%22normal-modes%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1639119391778%22%2C%22timestamp%22%3A1639123841822%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: recalculateVelocityAndAcceleration: N=9 i=1 velocity=Vector2(0, -0.7318838595241023), expected non-zero x component
Error: Assertion failed: recalculateVelocityAndAcceleration: N=9 i=1 velocity=Vector2(0, -0.7318838595241023), expected non-zero x component
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/assert/js/assert.js:25:13)
at OneDimensionModel.recalculateVelocityAndAcceleration (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/normal-modes/js/one-dimension/model/OneDimensionModel.js:288:13)
at OneDimensionModel.setVerletPositions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/normal-modes/js/one-dimension/model/OneDimensionModel.js:257:10)
at OneDimensionModel.singleStep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/normal-modes/js/one-dimension/model/OneDimensionModel.js:230:12)
at OneDimensionModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/normal-modes/js/one-dimension/model/OneDimensionModel.js:210:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/joist/js/Sim.js:258:22
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/axon/js/Action.js:195:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/joist/js/Sim.js:787:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/joist/js/Sim.js:776:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1639119391778/chipper/dist/js/joist/js/Sim.js:757:12)
id: Bayes Chrome
Snapshot from 12/9/2021, 11:56:31 PM
```

**Comment by pixelzoom** [comment] 2021-12-10 15:54
Duplicate of https://github.com/phetsims/normal-modes/issues/56.

**Closed by pixelzoom** 2021-12-10 15:54 UTC
Labels: type:automated-testing
