### ISSUE TITLE
Keep Normal Mode Amplitudes title visible when AccordionBox is expanded

### ISSUE THREAD

**Issue by arouinfar** [phetsims/normal-modes#77] opened 2021-11-02 21:17 UTC
For https://github.com/phetsims/qa/issues/724

The Normal Mode Amplitudes matrix on the Two Dimensions screen is really abstract. In general, this representation needs a bit of design work to make it more interpretable and clearly interactive. That goes way beyond the scope of the prototype. 

However, I think the representation would be a bit clearer if the title of the AccordionBox remained visible when it was expanded. Here's a mockup of what it would look like. Overall, the AccordionBox would be a bit taller, but there's room for it.
![image](https://user-images.githubusercontent.com/8419308/139951950-14a67b84-751c-491f-a3a9-d69555f9becb.png)

**Comment by pixelzoom** [comment] 2021-11-03 00:18
I'm confused. This is a duplicate of https://github.com/phetsims/normal-modes/issues/59, which we previously decided would not be addressed for the prototype.  Are you assigning this to me because you do want it addressed for the prototype?

**Comment by pixelzoom** [comment] 2021-11-03 15:00
Sigh... Why is nothing every easy with AccordionBox.  The screenshot below shows what happens where the title is made visible.  No idea how much work is involved in fixing this. @arouinfar how badly do you want this for the prototype?

<img width="1100" alt="screenshot_1403" src="https://user-images.githubusercontent.com/3046552/140085529-571902a2-dac2-469f-80ab-3e9c2a401469.png">

**Comment by arouinfar** [comment] 2021-11-03 15:45
> This is a duplicate of #59, which we previously decided would not be addressed for the prototype.

I don't remember making an explicit decision about that issue, sorry. 

>  @arouinfar how badly do you want this for the prototype?

I think there are serious usability issues with this representation in its current state. It's extremely abstract and lacks the labels that were in the Flash version, and if I didn't already know what it represented, I would be confused. It's completely unintuitive to collapse the AccordionBox to see its title, and students generally don't close things once they've been opened, anyway. 

Perhaps a compromise would be to change the default state so it starts closed. Students will see the title before expanding the AccordionBox so they will have more context for the representation. Would you have any objections to this change @ariel-phet?

**Comment by ariel-phet** [comment] 2021-11-03 16:47
@arouinfar I agree that this representation is a big part of the crux of taking this sim from the "prototype" version to the finish line. I would love to improve it, but I think that sort of improvement is beyond the scope of the prototype, as there is a fair bit of design work needed.

I think having the Accordion Box closed by default is a reasonable solution. Unless @kathy-phet wants to actually "take this sim to the finish line" I have been trying to go with the though of what is the bare minimum to get a reasonable prototype out. Unfortunately, this 2d amplitudes representation needs a fair bit of work to be clear.

If we wanted to be really hacky, maybe we toss an "info button" somewhere and just have a simple description of what this representation is stuck into a dialog. 

Anyhow, @pixelzoom having this unintuitive representation closed by default seems to be the quickest compromise.

**Comment by pixelzoom** [comment] 2021-11-03 16:57
I'm not wild about starting with this accodion box closed. 

How about this plan?
* Create the 1.0 RC branch asap, to minimize the possibly of new regressions in master.
* I'll spend up to 1 hour trying to fix the layout of this accordion box so that the title can be shown while it's closed. If I can make it work, I'll patch the 1.0 branch.
* If I can't get it to work in < 1 hour, then we'll leave it "as is" and make the accordion box closed by default.

**Comment by ariel-phet** [comment] 2021-11-03 17:07
@pixelzoom that sounds good.

**Comment by pixelzoom** [comment] 2021-11-03 18:27
Got this working, pushed to master and 1.0 branches. Screenshot below.

@arouinfar please verify in master, close if it looks OK. Then I'll proceed with RC testing. 

<img width="1098" alt="screenshot_1404" src="https://user-images.githubusercontent.com/3046552/140170564-a360b225-b135-4b96-bc2d-6cf8ca8966ee.png">

**Comment by pixelzoom** [comment] 2021-11-03 19:27
Great. Closing this issue. Onward to RC.

**Closed by pixelzoom** 2021-11-03 19:28 UTC
Labels: design:general, status:ready-for-review

**Comment by pixelzoom** [comment] 2021-11-05 15:54
Verified in 1.0.0-rc.1.
