### ISSUE TITLE
CT bad result of recalculateVelocityAndAcceleration

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/normal-modes#62] opened 2021-02-08 16:37 UTC
```
normal-modes : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/normal-modes/normal-modes_en.html?continuousTest=%7B%22test%22%3A%5B%22normal-modes%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612669954814%22%2C%22timestamp%22%3A1612706217495%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: bad result of recalculateVelocityAndAcceleration
Error: Assertion failed: bad result of recalculateVelocityAndAcceleration
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/assert/js/assert.js:25:13)
at OneDimensionModel.recalculateVelocityAndAcceleration (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/normal-modes/js/one-dimension/model/OneDimensionModel.js:341:13)
at OneDimensionModel.setVerletPositions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/normal-modes/js/one-dimension/model/OneDimensionModel.js:310:10)
at OneDimensionModel.singleStep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/normal-modes/js/one-dimension/model/OneDimensionModel.js:281:12)
at OneDimensionModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/normal-modes/js/one-dimension/model/OneDimensionModel.js:261:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/joist/js/Sim.js:282:22
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/axon/js/Action.js:225:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/joist/js/Sim.js:1074:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/joist/js/Sim.js:1064:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612669954814/joist/js/Sim.js:1042:12)
id: Bayes Chrome
Snapshot from 2/6/2021, 8:52:34 PM
```

**Comment by pixelzoom** [comment] 2021-11-08 20:32
Duplicate of #56. Closing.

**Closed by pixelzoom** 2021-11-08 20:32 UTC
Labels: type:automated-testing
