### ISSUE TITLE
Screenshot may not match sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/normal-modes#75] opened 2021-11-02 16:31 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/724. Fairly minor.
On the first screen, if the waves in the Normal Modes box are large enough that they are cut off, then in a screen shot, they may not be cut off.
**Steps to reproduce**
1. Go to the first screen
2. Create a wave where the first wave in the normal modes box on the right is cut off (I find it easiest to do with this wave.
3. Take a screenshot in the PhET Menu

**Visuals**
Actual Sim:
<img width="959" alt="notmatched" src="https://user-images.githubusercontent.com/41024075/139906407-3cf85f33-e45e-48cd-84db-705d5dcd283d.png">
Screenshot:
![Normal Modes screenshot (1)](https://user-images.githubusercontent.com/41024075/139906482-ffb97b53-9533-405a-80b3-72438be5a35f.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Normal Modes‬
URL: https://phet-dev.colorado.edu/html/normal-modes/1.0.0-dev.5/phet/normal-modes_en_phet.html
Version: 1.0.0-dev.5 2021-11-01 21:43:06 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2021-11-02 16:37
@KatieWoe It looks to me like there's a step missing in your description. Did you pause the sim, and take the screenshot with the sim paused?

**Comment by KatieWoe** [comment] 2021-11-02 16:41
Yes, so that I could make sure the timing was right and the same for when I took it with the phet menu as when I took it with the computer's tools

**Comment by pixelzoom** [comment] 2021-11-02 16:52
OK. So the correct steps are:

1. Go to the first screen
2. Pause the sim
3. Pull all 3 masses fully down, so that the mode 1 waveform will appear to be clipped in the Normal Modes accordion box.
4. Take a screenshot in the PhET Menu. Note that the mode 1 waveform is not clipped in the screenshot.

I reproduced this on macOS 12.0.1 + Chrome 95.0.4638.69 + 15.1 (17612.2.9.1.20).  So it does not appear to be browser or OS-specific. 

My recommendation is to ignore this, since the screenshot actually looks better than the sim. Assigning to @arouinfar for a decision. If you want to do something about this, the next step is to assign to @jonathanolson for investigation.

**Comment by Nancy-Salpepi** [comment] 2021-11-02 17:29
Since this issues deals with waveforms being clipped, I wanted to mention that in the flash version, they aren't. 
![normalmodes](https://user-images.githubusercontent.com/87318828/139915614-afd93d42-8ad3-4950-99e0-07eb3c5a689e.gif)

**Comment by pixelzoom** [comment] 2021-11-02 17:42
Thanks @Nancy-Salpepi.  This may have been a design decision for the HTML5 version? I'm not really sure - this sim was developed by a 3rd party, and I'm not the responsible dev.  (There currently is no responsible dev.)

@arouinfar Also your call on whether you want to change the rendering behavior of these waveforms.

**Comment by arouinfar** [comment] 2021-11-02 20:25
> This may have been a design decision for the HTML5 version?

In [dev.1](https://phet-dev.colorado.edu/html/normal-modes/1.0.0-dev.1/phet/normal-modes_en_phet.html) the clipping only occurred at the boundaries of the panel, but the individual modes could overlap one another
![image](https://user-images.githubusercontent.com/8419308/139945238-86bf8207-bdab-484a-a295-917f829024fb.png)

We decided that the max amplitude of the normal mode should fit in the space to avoid the overlap, but I don't think it was actually implemented. This is something that should be done in conjunction with limiting the displacement of the masses which will be done for the final version of this sim.

> My recommendation is to ignore this

Agreed. This is something that can be ignored for the prototype. Since the normal modes shouldn't get clipped in the final version, I think this issue can be closed.

**Closed by arouinfar** 2021-11-02 20:25 UTC
Labels: type:bug
